import math

# Function to calculate the n-th Fibonacci number using the closed-form formula (Binet's formula)
def fibonacci_math(n):
    a = (1 + math.sqrt(5)) / 2  # Golden ratio
    b = (1 - math.sqrt(5)) / 2  # Conjugate of the golden ratio
    # Apply Binet's formula and round to nearest integer
    return round((math.pow(a, n) - math.pow(b, n)) / math.sqrt(5))




# Recursive implementation of Fibonacci sequence
# Returns the n-th Fibonacci number
def fibonacci_recursion(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci_recursion(n-1) + fibonacci_recursion(n-2)

# Initialize a global list to store Fibonacci numbers
arrays = []
# Dynamic programming approach to calculate Fibonacci numbers up to n
# Stores all Fibonacci numbers in the 'arrays' list and returns the n-th Fibonacci number
def fibonacci_dynamic_plan(n):
    arrays.append(0)  # Append the first Fibonacci number (0) to the list
    a, b = 0, 1       # Initialize first two Fibonacci numbers
    if n == 0:
        return 0      # Return 0 if n is 0
    arrays.append(1)  # Append the second Fibonacci number (1) to the list
    if n == 1:
        return 1      # Return 1 if n is 1
    for i in range(2, n+1):
        # Update Fibonacci numbers using iteration
        a, b = b, a + b
        arrays.append(b)  # Store each Fibonacci number in the list
    return b  # Return the n-th Fibonacci number


# Main function for user interaction
def main():
    while True:
        try:
            input_variable = int(input('Please input a positive number: '))
            if input_variable < 0:
                print(f"This is a negative number")
                break
            arrays.clear()  # Clear the list before generating new Fibonacci numbers
            # Print the n-th Fibonacci number using dynamic programming
            print(f'The final number is {fibonacci_dynamic_plan(input_variable)}')
            # Print the n-th Fibonacci number using the mathematical formula
            print(f'The final number from fibonacci_math is {fibonacci_math(input_variable)}') 
            # Print all Fibonacci numbers generated by the dynamic approach
            print(*arrays, sep=', ')
        except ValueError:
            print("WARNING: This is not an integer! Please input again", end="")


if __name__ == "__main__":
    # Demonstration of power calculations: 3^i using math.pow() and 3**i
    for i in range(1, 9, 2):
        print(f'{i}:', f'math.pow: {math.pow(3, i)}', f'multiply: {3**i}')
    
    # Demonstration of repeated multiplication (4^4)
    sum = 1
    multiply = 4
    for j in range(0, 4, 1):
        sum *= multiply
    print(f'Result is: {sum}')
    
    # Call main function to start Fibonacci program
    main()
